### ISSUE TITLE
Scrape directories are empty after scrape

### ISSUE THREAD

**Issue by kn0w0n3** [Argonne-National-Laboratory/torantula#4]
A directory is created for each scrape, but no other information is ever recorded there. I am seeing a lot of "[root] INFO: ERROR DETECTED: Ignoring non-200 response" messages in the log. Any ideas why no data is being retrieved for the scrape? Thanks

Empty scrape folders  
![empty_scrape_folders](https://user-images.githubusercontent.com/22214754/200988905-8b1bc135-68f6-40aa-80dc-4df78869663a.png)  

Some log info  
![log-file](https://user-images.githubusercontent.com/22214754/200988951-5f0e43a2-4332-435d-9602-f065b2415bcf.png)    

Torantula GUI WIP
![torantula-ng-11-9-22](https://user-images.githubusercontent.com/22214754/200989778-9876c495-ffe0-4b20-b6de-c558223ee2ea.gif)

**Comment by rolandvarriale** [comment]
I think I have seen this when there is some filtering happening at the bridge/dns stage. E.g., if there is a firewall blocking the tor bridge it can’t resolve the onion sites and throws those errors

**Comment by kn0w0n3** [comment]
That makes sense. I will look into that. I did get the clear scan working just now.  The clear scan initially had empty directories as well, but that was because I was still using sites.txt instead of startingListURLS.txt. I am seeing all of the files populate for the clear scrape now. Appreciate the help!
